sudo: required
services:
  - docker

before_install:
  - docker image build -t docker-react -f dev.Dockerfile .

script:
  - docker container run docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-108379538206"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWSS_ACCESS_KEY"
  secret_access-key:
    secure: "$AWS_SECRET_KEY"